name: 'terrasync'
version: '1.0.0'

profile: 'terrasync'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  terrasync:
    staging:
      +materialized: external
    silver:
      +materialized: table
      +schema: silver
      +contract:
        enforced: true
    exports:
      +materialized: external
